[proxmox_hosts]
proxmox_node ansible_host=192.168.1.19 ansible_user=root

[postgres_nodes]
postgres_db ansible_host=192.168.1.20 ansible_user=root

[app_nodes]
phoenix_app ansible_host=192.168.1.21 ansible_user=root

[all:vars]
ansible_python_interpreter=/usr/bin/python3
